### ISSUE TITLE
[BUG] Branches with open PRs are marked stale

### ISSUE THREAD

**Issue by ryan-dahlia** [crs-k/stale-branches#1125]
Thank you @crs-k for creating this action!

**Describe the bug**
Branches that are associated with an open (draft) pull request are still marked stale. The README states that by default, a stale branch is one that '...has no open pull requests."

**To Reproduce**
Create a draft pull request of a sufficient age to be stale. Run this action.

**Expected behavior**
The branch associated with a PR would not be marked stale by this action.

**Additional context**
Since we also use `actions/stale@v9` to manage stale PRs, we do not want `crs-k/stale-branches` to mark those PR branches as stale. 

Here is our config for completeness, but I don't think it's affecting the behavior:
```yaml
- name: Stale branches
  uses: crs-k/stale-branches@v3.1.4
  with:
    stale-branch-label: ${{ env.STALE_BRANCH_LABEL }}
    days-before-stale: 7
    days-before-delete: 14
    tag-commiter: true
```

**Comment by crs-k** [comment]
hey, thanks for posting this, i'll look into it. we also use this with actions/stale and have the thresholds for that set just a few days lower than the stale-branches action to avoid collisions. also most likely why i haven't found this defect.

**Comment by ryan-dahlia** [comment]
Awesome, thanks for looking into it!

**Comment by crs-k** [comment]
hey @ryan-dahlia, Please give `v4.1.0` a try. I've added an optional input to check for pull requests against branches prior to processing them. To avoid a breaking change, this is defaulted to false. I've also removed that bullet from the documentation's definition of a stale branch.

You will want to add `pr-check: true` to your workflow file to enable the feature.

You should see branches that have a PR against them skipped with the following message:
![image](https://github.com/crs-k/stale-branches/assets/26232872/af7c5826-978f-4ee6-9c34-fd7db1cbbfb5)

**Comment by ryan-dahlia** [comment]
Hey @crs-k thanks again for incorporating this feature!

It seems to be working well (hard to test the negative case in a live repo).
However it does not appear that Draft PRs are counted as open. WDYT about adding draft PRs too?

**Comment by MatthewMiddlehurst** [comment]
Thanks for adding this feature. +1 to draft PRs, I had assumed they were included with this toggle. Would be great if they could be included @crs-k.

**Comment by crs-k** [comment]
hey @MatthewMiddlehurst & @ryan-dahlia 

i could use some more info on this one. assume all conditions are met for these to be stale. see chart and screenshots below

if i run the current action (`v4.1.0`) from `main`, it will recognize that branch `include-draft-prs-in-pr-check` has two incoming PRs, one `draft` and one `notDraft`. As a result, the action will _**exclude**_ branch `include-draft-prs-in-pr-check`.
![image](https://github.com/crs-k/stale-branches/assets/26232872/40263ab1-ddaa-4a08-ae05-2a400bad0404)

however, in the case of `outgoing-PR`, `draft`, and `notDraft`, these will currently be **_included_** on the basis of not having incoming PRs against them, regardless of having open outgoing PRs against their targets.

**is the desired outcome to have any branch with active incoming AND outgoing PRs open to be excluded with the `pr-check` input?**

```mermaid
gitGraph
commit
checkout main
commit
commit
branch include-draft-prs-in-pr-check
checkout include-draft-prs-in-pr-check
commit
commit
branch draft
checkout draft
commit
checkout include-draft-prs-in-pr-check
branch notDraft
checkout notDraft
commit
checkout include-draft-prs-in-pr-check
merge draft
merge notDraft
checkout main
merge include-draft-prs-in-pr-check
commit
branch outgoing-PR
checkout outgoing-PR
commit
checkout main
merge outgoing-PR
commit
```

regarding incoming draft PRs not being included, i am not able to reproduce that. here is my workflow for reference:

```
name: Stale Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1-5'

permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v4.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        days-before-stale: 1
        comment-updates: true
        tag-committer: true
        days-before-delete: 180
        max-issues: 20
        stale-branch-label: 'stale branch 🗑️'
        branches-filter-regex: '^((?!dependabot))'
        pr-check: true
```
