### ISSUE TITLE
[FEATURE] Dry Run, or ability to not delete branches

### ISSUE THREAD

**Issue by manveer-ce** [crs-k/stale-branches#1186]
Hi,

Nice work on this runner, thanks.

Im using this to delete old release branches after a couple days.
Im going to also use it to create issues for and tag people for old , non-release, branches as well. 

name: 'Delete-Stale-Release-Branches'
```
on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch:

jobs:
  delete-stale-release-branches:
    runs-on: arc-runner-set

    steps:
      - name: Release Branches
        uses: crs-k/stale-branches@v5.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          days-before-stale: 3 
          days-before-delete: 7 
          comment-updates: false
          max-issues: 20
          tag-committer: false
          stale-branch-label: 'stale branch 🗑️'
          compare-branches: 'info'
          branches-filter-regex: '^release\/.*' # regex for 'release/*' branches
          pr-check: true

      # Check for old branches but don't delete them
      - name: Old Branches
        uses: crs-k/stale-branches@v5.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          days-before-stale: 30
          days-before-delete: 999
          comment-updates: false
          max-issues: 20
          tag-committer: true
          stale-branch-label: 'stale branch 🗑️'
          compare-branches: 'save'
          pr-check: true
```

If I could change that second one to instead be like `days-before-delete: 0` or `dry-run:true` so it does everything except delete the branch, that would be nice.
