### ISSUE TITLE
[BUG] Unable to retrieve pull requests

### ISSUE THREAD

**Issue by Shamik-07** [crs-k/stale-branches#1429]
**Describe the bug**
While running the github action, i am getting the following error for certain branches:
```sh
Error: Failed to retrieve pull requests for feat_ETL_pipeline_V01. Error: Resource not accessible by integration - https://docs.github.com/rest/pulls/pulls#list-pull-requests
```

**To Reproduce**
Running the github action:
```yaml

# Removes stale branches
name: Stale Branches

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v7.0.1
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        days-before-stale: 60
        days-before-delete: 90
```

**Expected behavior**
We aren't supposed to see this error.

**Additional context**
